-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-09-14 18:10:00 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   Group:    G061
--   Authors: Stefan Sudar, Amy Liu, Nguyen Khang

set echo on

SPOOL rcl_schema_output.txt

DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE book_copy CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE borrower_class CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE catalogue_author CASCADE CONSTRAINTS;

DROP TABLE catalogue_entry CASCADE CONSTRAINTS;

DROP TABLE catalogue_publisher CASCADE CONSTRAINTS;

DROP TABLE catalogue_subject CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reserve CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE author (
    author_id NUMBER(7) NOT NULL,
    author_fname VARCHAR2(50) NOT NULL,
    author_lname VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN author.author_id IS
    'Author number';

COMMENT ON COLUMN author.author_fname IS
    'Author first name';

COMMENT ON COLUMN author.author_lname IS
    'Author last name
';

ALTER TABLE author
    ADD CONSTRAINT author_pk PRIMARY KEY (
        author_id
    );

CREATE TABLE book (
    book_isbn_no CHAR(13) NOT NULL,
    book_type CHAR(1) NOT NULL,
    catalogue_call_no VARCHAR2(50) NOT NULL
);

ALTER TABLE book
    ADD CONSTRAINT chk_booktype CHECK (
        book_type IN ( 'H', 'L', 'P' )
    );

COMMENT ON COLUMN book.book_isbn_no IS
    'ISBN-13 number of book';

COMMENT ON COLUMN book.book_type IS
    'Type of book, either hardcover or loose leaf';

COMMENT ON COLUMN book.catalogue_call_no IS
    'Call number of catalogue (Dewey Decimal call number)';

ALTER TABLE book
    ADD CONSTRAINT book_pk PRIMARY KEY (
        book_isbn_no
    );

CREATE TABLE book_copy (
    book_copy_id NUMBER(7) NOT NULL,
    branch_code NUMBER(7) NOT NULL,
    book_copy_flag CHAR(1) NOT NULL,
    book_copy_purchase_price NUMBER(7) NOT NULL,
    book_copy_status CHAR(1) NOT NULL,
    book_isbn_no CHAR(13) NOT NULL
);

ALTER TABLE book_copy
    ADD CONSTRAINT chk_bookcopyflag CHECK (
        book_copy_flag IN ( 'A', 'L', 'R' )
    );

ALTER TABLE book_copy
    ADD CONSTRAINT check_book_copy_status CHECK (
        book_copy_status IN ( 'A', 'D', 'L', 'S' )
    );

COMMENT ON COLUMN book_copy.book_copy_id IS
    'Book copy ID';

COMMENT ON COLUMN book_copy.branch_code IS
    'Branch code';

COMMENT ON COLUMN book_copy.book_copy_flag IS
    'Flag indicating whether book is on counter reserve, on loan or available for borrowing';

COMMENT ON COLUMN book_copy.book_copy_purchase_price IS
    'Purchase price of book';

COMMENT ON COLUMN book_copy.book_copy_status IS
    'The status of book copy, either available, stolen, lost or damaged.';

COMMENT ON COLUMN book_copy.book_isbn_no IS
    'ISBN-13 number of book';

ALTER TABLE book_copy
    ADD CONSTRAINT book_copy_pk PRIMARY KEY (
        book_copy_id,
        branch_code
    );

CREATE TABLE borrower (
    borrower_no NUMBER(7) NOT NULL,
    borrower_fname VARCHAR2(50) NOT NULL,
    borrower_lname VARCHAR2(50) NOT NULL,
    borrower_class CHAR(1) NOT NULL,
    borrower_status CHAR(1) NOT NULL,
    borrower_street VARCHAR2(30) NOT NULL,
    borrower_city VARCHAR2(20) NOT NULL,
    borrower_state VARCHAR2(20) NOT NULL,
    borrower_pcode CHAR(4) NOT NULL,
    borrower_class_no NUMBER(7) NOT NULL,
    branch_code NUMBER(7) NOT NULL
);

ALTER TABLE borrower
    ADD CONSTRAINT chk_borrowerstatus CHECK (
        borrower_status IN ( 'B', 'P' )
    );

COMMENT ON COLUMN borrower.borrower_no IS
    'Borrower number';

COMMENT ON COLUMN borrower.borrower_fname IS
    'Borrower''s first name';

COMMENT ON COLUMN borrower.borrower_lname IS
    'Borrower''s last name';

COMMENT ON COLUMN borrower.borrower_class IS
    'Borrower''s class, currently either Adult, Child or Organisation';

COMMENT ON COLUMN borrower.borrower_status IS
    'The status of the borrower, either Permitted or Banned';

COMMENT ON COLUMN borrower.borrower_street IS
    'Borrower street address ';

COMMENT ON COLUMN borrower.borrower_city IS
    'Borrower address city';

COMMENT ON COLUMN borrower.borrower_state IS
    'Borrower address state';

COMMENT ON COLUMN borrower.borrower_pcode IS
    'Borrower post code address';

COMMENT ON COLUMN borrower.borrower_class_no IS
    'Borrower''s class number';

COMMENT ON COLUMN borrower.branch_code IS
    'Branch code';

ALTER TABLE borrower
    ADD CONSTRAINT borrower_pk PRIMARY KEY (
        borrower_no
    );

CREATE TABLE borrower_class (
    borrower_class_no NUMBER(7) NOT NULL,
    borrower_class_name VARCHAR2(50) NOT NULL,
    borrower_class_loan_limit NUMBER(2) NOT NULL,
    borrower_class_loan_period NUMBER(3) NOT NULL
);

ALTER TABLE borrower_class
    ADD CHECK (
        borrower_class_name IN ( 'A', 'C', 'O' )
    );

COMMENT ON COLUMN borrower_class.borrower_class_no IS
    'Borrower''s class number';

COMMENT ON COLUMN borrower_class.borrower_class_name IS
    'Borrower class name is currently either Adult, Child or Organisation. This may be expanded in the future. ';

COMMENT ON COLUMN borrower_class.borrower_class_loan_limit IS
    'Borrow limit for borrower class';

COMMENT ON COLUMN borrower_class.borrower_class_loan_period IS
    'Standard loan period in days of borrower class ';

ALTER TABLE borrower_class
    ADD CONSTRAINT borrower_class_pk PRIMARY KEY (
        borrower_class_no
    );

CREATE TABLE branch (
    branch_code NUMBER(7) NOT NULL,
    branch_name VARCHAR2(50) NOT NULL,
    branch_addr VARCHAR2(100) NOT NULL,
    branch_phone CHAR(10) NOT NULL,
    lga_code NUMBER(7) NOT NULL,
    manager_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'Branch code';

COMMENT ON COLUMN branch.branch_name IS
    'Branch name';

COMMENT ON COLUMN branch.branch_addr IS
    'Branch address';

COMMENT ON COLUMN branch.branch_phone IS
    'Branch phone number';

COMMENT ON COLUMN branch.lga_code IS
    'Local Government Agencies'' code';

COMMENT ON COLUMN branch.manager_id IS
    'Manager ID';

ALTER TABLE branch
    ADD CONSTRAINT branch_pk PRIMARY KEY (
        branch_code
    );

CREATE TABLE catalogue_author (
    catalogue_call_no VARCHAR2(50) NOT NULL,
    author_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN catalogue_author.catalogue_call_no IS
    'Call number of catalogue (Dewey Decimal call number)';

COMMENT ON COLUMN catalogue_author.author_id IS
    'Author number';

ALTER TABLE catalogue_author
    ADD CONSTRAINT catalogue_author_pk PRIMARY KEY (
        catalogue_call_no,
        author_id
    );

CREATE TABLE catalogue_entry (
    catalogue_call_no VARCHAR2(50) NOT NULL,
    catalogue_title VARCHAR2(50) NOT NULL,
    catalogue_contents VARCHAR2(500) NOT NULL,
    catalogue_pub_year DATE NOT NULL,
    catalogue_classification CHAR(1) NOT NULL,
    catalogue_reading_lvl VARCHAR2(2),
    catalogue_no_pages VARCHAR2(4) NOT NULL,
    catalogue_ed VARCHAR2(50),
    catalogue_lang VARCHAR2(50) NOT NULL,
    catalogue_note VARCHAR2(100)
);

ALTER TABLE catalogue_entry
    ADD CONSTRAINT chk_cataclass CHECK (
        catalogue_classification IN ( 'F', 'R' )
    );

ALTER TABLE catalogue_entry
    ADD CONSTRAINT chk_reading_level CHECK (
        catalogue_reading_lvl BETWEEN '1' AND '30'
    );

COMMENT ON COLUMN catalogue_entry.catalogue_call_no IS
    'Call number of catalogue (Dewey Decimal call number)';

COMMENT ON COLUMN catalogue_entry.catalogue_title IS
    'Catalogue title';

COMMENT ON COLUMN catalogue_entry.catalogue_contents IS
    'Catalogue contents';

COMMENT ON COLUMN catalogue_entry.catalogue_pub_year IS
    'Year published';

COMMENT ON COLUMN catalogue_entry.catalogue_classification IS
    'Catalogue classifcation as fiction or reference';

COMMENT ON COLUMN catalogue_entry.catalogue_reading_lvl IS
    'Reading level (1-30) for catalogue entry is recorded for Fiction entries';

COMMENT ON COLUMN catalogue_entry.catalogue_no_pages IS
    'Number of pages of catalogue entry';

COMMENT ON COLUMN catalogue_entry.catalogue_ed IS
    'Edition of the catalogue entry';

COMMENT ON COLUMN catalogue_entry.catalogue_lang IS
    'Type of language for catalogue entry';

COMMENT ON COLUMN catalogue_entry.catalogue_note IS
    'Note for catalogue entry ';

ALTER TABLE catalogue_entry
    ADD CONSTRAINT catalogue_entry_pk PRIMARY KEY (
        catalogue_call_no
    );

CREATE TABLE catalogue_publisher (
    catalogue_call_no VARCHAR2(50) NOT NULL,
    publisher_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN catalogue_publisher.catalogue_call_no IS
    'Call number of catalogue (Dewey Decimal call number)';

COMMENT ON COLUMN catalogue_publisher.publisher_id IS
    'Publisher id
';

CREATE UNIQUE INDEX catalogue_publisher__idx ON
    catalogue_publisher (
        catalogue_call_no
    ASC );

ALTER TABLE catalogue_publisher
    ADD CONSTRAINT catalogue_publisher_pk PRIMARY KEY (
        catalogue_call_no,
        publisher_id
    );

CREATE TABLE catalogue_subject (
    catalogue_call_no VARCHAR2(50) NOT NULL,
    subject_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN catalogue_subject.catalogue_call_no IS
    'Call number of catalogue (Dewey Decimal call number)';

COMMENT ON COLUMN catalogue_subject.subject_id IS
    'subject id';

ALTER TABLE catalogue_subject
    ADD CONSTRAINT catalogue_subject_pk PRIMARY KEY (
        catalogue_call_no,
        subject_id
    );

CREATE TABLE lga (
    lga_code NUMBER(7) NOT NULL,
    lga_name VARCHAR2(50) NOT NULL,
    lga_size NUMBER(7) NOT NULL,
    lga_contact_name VARCHAR2(50) NOT NULL,
    lga_contact_phone CHAR(10) NOT NULL
);

COMMENT ON COLUMN lga.lga_code IS
    'Local Government Agencies'' code';

COMMENT ON COLUMN lga.lga_name IS
    'Local Government Agencies'' name';

COMMENT ON COLUMN lga.lga_size IS
    'Local Government Agencies'' area size';

COMMENT ON COLUMN lga.lga_contact_name IS
    'Local Government Agencies'' contract personal name';

COMMENT ON COLUMN lga.lga_contact_phone IS
    'Local Government Agencies'' contact phone number';

ALTER TABLE lga
    ADD CONSTRAINT lga_pk PRIMARY KEY (
        lga_code
    );

CREATE TABLE loan (
    loan_no NUMBER(7) NOT NULL,
    loan_current_date_time DATE NOT NULL,
    book_copy_id NUMBER(7) NOT NULL,
    branch_code NUMBER(7) NOT NULL,
    loan_due_date DATE NOT NULL,
    loan_actual_return_date_time DATE,
    loan_fine_amount NUMBER(7),
    loan_fine_paid_date DATE,
    borrower_no NUMBER(7) NOT NULL
);

COMMENT ON COLUMN loan.loan_no IS
    'Loan number (Surrogate PK)';

COMMENT ON COLUMN loan.loan_current_date_time IS
    'The time and date that the loan starts';

COMMENT ON COLUMN loan.book_copy_id IS
    'Book copy ID';

COMMENT ON COLUMN loan.branch_code IS
    'Branch code';

COMMENT ON COLUMN loan.loan_due_date IS
    'The date that the borrower has to return the loan, recorded automatically based on the current date and borrower class loan period.';

COMMENT ON COLUMN loan.loan_actual_return_date_time IS
    'The actual date and time that borrower returns the loan';

COMMENT ON COLUMN loan.loan_fine_amount IS
    'The amount of fine that borrower have to pay
Loan_fine_amount = (loan_actual_return_date - loan_due_date) * fine_rate';

COMMENT ON COLUMN loan.loan_fine_paid_date IS
    'The date and time that borrower have to pay the fine';

COMMENT ON COLUMN loan.borrower_no IS
    'Borrower number';

ALTER TABLE loan
    ADD CONSTRAINT loan_pk PRIMARY KEY (
        loan_no
    );

ALTER TABLE loan
    ADD CONSTRAINT loan_nk UNIQUE (
        loan_current_date_time,
        branch_code,
        book_copy_id
    );

CREATE TABLE manager (
    manager_id NUMBER(7) NOT NULL,
    manager_fname VARCHAR2(50) NOT NULL,
    manager_lname VARCHAR2(50) NOT NULL,
    manager_phone CHAR(10) NOT NULL,
    branch_code NUMBER(7) NOT NULL
);

COMMENT ON COLUMN manager.manager_id IS
    'Manager ID';

COMMENT ON COLUMN manager.manager_fname IS
    'Manager first name';

COMMENT ON COLUMN manager.manager_lname IS
    'Manager last name';

COMMENT ON COLUMN manager.manager_phone IS
    'Manager phone number';

COMMENT ON COLUMN manager.branch_code IS
    'Branch code';

CREATE UNIQUE INDEX manager__idx ON
    manager (
        branch_code
    ASC );

ALTER TABLE manager
    ADD CONSTRAINT manager_pk PRIMARY KEY (
        manager_id
    );

CREATE TABLE publisher (
    publisher_id NUMBER(7) NOT NULL,
    publisher_name VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN publisher.publisher_id IS
    'Publisher id
';

COMMENT ON COLUMN publisher.publisher_name IS
    'Publisher name';

ALTER TABLE publisher
    ADD CONSTRAINT publisher_pk PRIMARY KEY (
        publisher_id
    );

CREATE TABLE reserve (
    reserve_id NUMBER(7) NOT NULL,
    reserve_date_time DATE NOT NULL,
    borrower_no NUMBER(7) NOT NULL,
    book_copy_id NUMBER(7) NOT NULL,
    branch_code NUMBER(7) NOT NULL,
    reserve_phone_no CHAR(10) NOT NULL
);

COMMENT ON COLUMN reserve.reserve_id IS
    'Reserve (surrogate PK)';

COMMENT ON COLUMN reserve.reserve_date_time IS
    'The date and time the reservation of book copy is made';

COMMENT ON COLUMN reserve.borrower_no IS
    'Borrower number';

COMMENT ON COLUMN reserve.book_copy_id IS
    'Book copy ID';

COMMENT ON COLUMN reserve.branch_code IS
    'Branch code';

COMMENT ON COLUMN reserve.reserve_phone_no IS
    'Borrower''s phone number given for this specific reservation';

ALTER TABLE reserve
    ADD CONSTRAINT reserve_pk PRIMARY KEY (
        reserve_id
    );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_nk UNIQUE (
        reserve_date_time,
        branch_code,
        book_copy_id,
        borrower_no
    );

CREATE TABLE subject (
    subject_id NUMBER(7) NOT NULL,
    subject_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN subject.subject_id IS
    'subject id';

COMMENT ON COLUMN subject.subject_desc IS
    'subject description
';

ALTER TABLE subject
    ADD CONSTRAINT subject_pk PRIMARY KEY (
        subject_id
    );

ALTER TABLE catalogue_author
    ADD CONSTRAINT author_cat_author_fk FOREIGN KEY (
        author_id
    )
        REFERENCES author (
            author_id
        );

ALTER TABLE book_copy
    ADD CONSTRAINT book_book_copy_fk FOREIGN KEY (
        book_isbn_no
    )
        REFERENCES book (
            book_isbn_no
        );

ALTER TABLE loan
    ADD CONSTRAINT book_copy_loan FOREIGN KEY (
        book_copy_id,
        branch_code
    )
        REFERENCES book_copy (
            book_copy_id,
            branch_code
        );

ALTER TABLE reserve
    ADD CONSTRAINT book_copy_reserve FOREIGN KEY (
        book_copy_id,
        branch_code
    )
        REFERENCES book_copy (
            book_copy_id,
            branch_code
        );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_borrower_class_fk FOREIGN KEY (
        borrower_class_no
    )
        REFERENCES borrower_class (
            borrower_class_no
        );

ALTER TABLE loan
    ADD CONSTRAINT borrower_loan_fk FOREIGN KEY (
        borrower_no
    )
        REFERENCES borrower (
            borrower_no
        );

ALTER TABLE reserve
    ADD CONSTRAINT borrower_reserve_fk FOREIGN KEY (
        borrower_no
    )
        REFERENCES borrower (
            borrower_no
        );

ALTER TABLE book_copy
    ADD CONSTRAINT branch_book_copy_fk FOREIGN KEY (
        branch_code
    )
        REFERENCES branch (
            branch_code
        );

ALTER TABLE borrower
    ADD CONSTRAINT branch_borrower_fk FOREIGN KEY (
        branch_code
    )
        REFERENCES branch (
            branch_code
        );

ALTER TABLE catalogue_author
    ADD CONSTRAINT cat_entry_cat_author_fk FOREIGN KEY (
        catalogue_call_no
    )
        REFERENCES catalogue_entry (
            catalogue_call_no
        );

ALTER TABLE catalogue_publisher
    ADD CONSTRAINT cat_entry_cat_pub_fk FOREIGN KEY (
        catalogue_call_no
    )
        REFERENCES catalogue_entry (
            catalogue_call_no
        );

ALTER TABLE catalogue_subject
    ADD CONSTRAINT cat_entry_cat_subject_fk FOREIGN KEY (
        catalogue_call_no
    )
        REFERENCES catalogue_entry (
            catalogue_call_no
        );

ALTER TABLE book
    ADD CONSTRAINT catalogue_entry_book_fk FOREIGN KEY (
        catalogue_call_no
    )
        REFERENCES catalogue_entry (
            catalogue_call_no
        );

ALTER TABLE branch
    ADD CONSTRAINT lga_branch_fk FOREIGN KEY (
        lga_code
    )
        REFERENCES lga (
            lga_code
        );

ALTER TABLE branch
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY (
        manager_id
    )
        REFERENCES manager (
            manager_id
        );

ALTER TABLE manager
    ADD CONSTRAINT manager_branch_fkv2 FOREIGN KEY (
        branch_code
    )
        REFERENCES branch (
            branch_code
        );

ALTER TABLE catalogue_publisher
    ADD CONSTRAINT pub_cat_pub_fk FOREIGN KEY (
        publisher_id
    )
        REFERENCES publisher (
            publisher_id
        );

ALTER TABLE catalogue_subject
    ADD CONSTRAINT sub_cat_subject_fk FOREIGN KEY (
        subject_id
    )
        REFERENCES subject (
            subject_id
        );

-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            16
-- CREATE INDEX                             2
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off

set echo off